# Development environment specific configuration for user-service
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.example.userservice: DEBUG
    org.springframework.web: DEBUG
